start:
	g++	-c	../SString/String.cpp	../SString/StrImg.cpp	../SCommon/SClib.cpp	../SFile/SFile.cpp	../SFile/SConfig.cpp	../SFile/SLog.cpp	../SSystem/System.cpp	../STime/STime.cpp	../SGZip/SGZip.cpp	../SString/SConvert.cpp
#
	ar	-crv	SCommon.a	String.o	StrImg.o	SClib.o	SFile.o	SConfig.o	SLog.o	System.o	STime.o	SGZip.o	SConvert.o
